In [12]:
import numpy as np

def no_numpy_mult(first, second):
    """
    param first: list of "size" lists, each contains "size" floats
    param second: list of "size" lists, each contains "size" floats
    """

    M, K = len(first), len(second[0])
    result = [[0 for x in range(K)] for y in range(M)]
    for i in range(M):
        for j in range(K):
            res = 0
            for k in range(len(first[i])):
                res += first[i][k] * second[k][j]
            result[i][j] = res
    
    return result

def numpy_mult(first, second):
    """
    param first: np.array[size, size]
    param second: np.array[size, size]
    """
    
    return np.matmul(first, second)

for tt in range(100):
    np.random.seed(tt+228)
    
    N = 3
    a = [[np.random.randint(1, 10) for x in range(N)] for y in range(N)]
    b = [[np.random.randint(1, 10) for x in range(N)] for y in range(N)]

    M1 = no_numpy_mult(a, b)
    M2 = numpy_mult(np.array(a), np.array(b))

#     print(np.allclose(np.array(M1), M2))
    assert np.allclose(np.array(M1), M2)

print('Ok, all tests passed')

Ok, all tests passed


In [58]:
import numpy as np

def transform(X, a=1):
    """
    param X: np.array[batch_size, n]
    """
    Y = X.copy()
    Y[:, 1::2] = a
    Y[:, ::2] **= 3
    return np.concatenate((X, Y[:, ::-1]), 1)

x = np.array([[2,1,3,4,5]])
print(transform(x))

[[  2   1   3   4   5 125   1  27   1   8]]


In [48]:
a = np.array([[1, 2, 3], 
              [2, 4, 6]])
b = np.array([[2, 3, 4], 
              [8, 7, 2]])

print(a[:, ::-1])
# print(np.concatenate((a, b), 1))

[[3 2 1]
 [6 4 2]]


In [61]:
def encode(a):
    ans, count = [], []
    prev = np.min(a)-11
    for x in a:
        if x != prev:
            ans.append(x)
            count.append(1)
        else:
            count[-1] += 1
        prev = x
    return (np.array(ans), np.array(count))

print(encode([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3]))

(array([1, 2, 3, 1, 5, 2, 3]), array([1, 2, 2, 2, 2, 1, 2]))
